Introduction to Numpy - Lecture 1 - Creating Arrays 

In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2=[11,22,33,44]

In [6]:
my_lists = [my_list1, my_list2]

In [7]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [8]:
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
my_array2.shape


(2, 4)

In [11]:
my_array2.dtype

dtype('int64')

In [12]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
np.ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [14]:
np.empty(3)

array([  2.13882710e-314,   2.13882710e-314,   2.15852807e-314])

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
np.arange(3,6,10)

array([3])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(1,9,3)

array([1, 4, 7])

In [19]:
np.arange(1,10,3)

array([1, 4, 7])

NOTE: the range (a,b) always starts with 'a' and ends at a number 'x' < 'b'

Introduction to Numpy - Lecture 2 - Using arrays and scalars


In [5]:
from __future__ import division

In [6]:
5/2

2.5

In [8]:
arr1 = np.array([[1,2,3,4], [6,7,8,9]])

In [10]:
arr1

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [11]:
arr1*arr1

array([[ 1,  4,  9, 16],
       [36, 49, 64, 81]])

In [12]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.16666667,  0.14285714,  0.125     ,  0.11111111]])

In [14]:
arr1**2

array([[ 1,  4,  9, 16],
       [36, 49, 64, 81]])

Intro to Numpy - Lecture 3 - Indexing arrays

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[3]

3

In [21]:
arr[2:5]

array([2, 3, 4])

In [22]:
arr[1:5] = 10

In [23]:
arr

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [25]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[0:3]


array([1, 2, 3])

In [28]:
slice_of_arr = arr[0:3]

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
slice_of_arr[:] = 99

In [31]:
slice_of_arr

array([99, 99, 99])

In [32]:
arr

array([99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

NOTE: if you change slice_of_arr you change the part of the array in the original array, which avoids memeory problem. 

In [33]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr_2d[0]

array([1, 2, 3])

In [35]:
arr_2d[2]

array([7, 8, 9])

In [36]:
arr_2d[2][0]

7

NOTE; the combination of index and column gives you the value of the cell.

In [38]:
arr_2d[:2,:1]

array([[1],
       [4]])

In [57]:
arr2d = np.zeros((4,2))

In [58]:
arr2d

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [61]:
arr2d_length = arr2d.shape[0]

NOTE: This array.shape[0] gives you the number of "rows" in a 2D array.

In [62]:
arr2d_length

4

In [63]:
arr2d_length1 = arr2d.shape[1]

In [64]:
arr2d_length1

2

NOTE: whereas the array.shape[1] gives you the number of columns in a 2D array.

Intro to Numpy - Lecture 4 - Array Transnposition

In [65]:
arr2d.T

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [66]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr_2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [68]:
np.dot(arr_2d.T, arr_2d)

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

NOTE: this "np.dot" command use is important matrix algebra expression.

In [69]:
arr_3d = np.arange(30).reshape((3,2,5))

In [70]:
arr_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [71]:
arr_3d = np.arange(30).reshape((5,3,2))

In [72]:
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [73]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]],

       [[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]]])

Intro to Numpy - Lecture 5 - Universal Array Functions

In [87]:
arr = np.array([1,4,9,16])

In [88]:
arr

array([ 1,  4,  9, 16])

In [89]:
np.sqrt(arr)

array([ 1.,  2.,  3.,  4.])

In [90]:
np.exp(arr)

array([  2.71828183e+00,   5.45981500e+01,   8.10308393e+03,
         8.88611052e+06])

In [91]:
np.random.randn(5)

array([-1.24641752, -0.286968  ,  0.18996297,  1.23380553,  0.98318161])

NOTE: for more functions, check out http://docs.scipy.org/doc/numpy/reference/ufuncs.html

Lecture 6 - Array Processing

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
%matplotlib inline


In [6]:
points = np.arange(-5,5,0.1)

In [8]:
dx,dy = np.meshgrid(points,points)